### ISSUE TITLE
v1.2.0 - Promptor does not follow instructions / Duration is wrong

### ISSUE THREAD

**Issue by RhapsodyinBlack** [1038lab/ComfyUI-MiniMax-H3-Promptor#10]
Hi AILab

I really enjoyed using your custom node (v1.1.0). I did not have any problems and it worked great. However v1.2.0 has issues which makes it unusable (at least for me).

Issue 1 - Promptor does not follow instructions
Promptor ignores anything I put in the description box. It will generate whatever prompt it likes. Occasionally it will generate a blank prompt.

Issue 2 - Promptor does not respect Duration.
It will randomly pick a duration. In the examples below, the duration is set to 5s.

The first image is of v1.1.0. Everything is working ok. The prompt instructs the model to dance and it respects the duration of 5s.
<img width="1128" height="1060" alt="Image" src="https://github.com/user-attachments/assets/6464eb78-c44b-45e3-a389-cb00ee2d426e" />

This second image is of v1.2.0. Instead of dancing, the prompt describes a couple walking on the beach in the sunset. Duration is set to 5s but prompt has instructions up to 15s. Unfortunately, I did not screenshot the full 15s prompt.

<img width="1139" height="1078" alt="Image" src="https://github.com/user-attachments/assets/60de4b38-fbbd-49d0-b33b-0c5dd89a9e64" />

The third image is also of v.1.2.0.  Instead of a 5s dancing prompt, I get a 45s prompt of the subject exploring a building.

<img width="1120" height="1050" alt="Image" src="https://github.com/user-attachments/assets/465136cf-33c6-4f7a-a3d4-38722765a74f" />

The last 2 images are also of v.1.2.0. I changed the provider to gemma4:12b (still tested OK in config) and I get a [H3 Promptor Error - None]. The ollama window shows tokens were used but comfyui window show no prompt was returned. 

<img width="1137" height="1067" alt="Image" src="https://github.com/user-attachments/assets/7728d035-ea9c-43be-ad27-9707c3f1d968" />
<img width="1101" height="850" alt="Image" src="https://github.com/user-attachments/assets/5706498c-639a-4a1d-81cf-ccd2c49ccf41" />

Things I have tried:
1. Reinstalling v.1.2.0 (directly from git URL and also by upgrading from v1.1.0) via ComfyUI Manager)
2. Restarting ComfyUI between jobs.
3. Used Ollama gemma4:12b model as the provider for the promptor.
4.. Deleted and recreated the providers in the Comfyui settings (they test OK).
5. Reloaded/deleted/used new nodes in workflow after upgrading to v1.2.0.

Thank you very much - I hope this information is useful. I have since downgraded back to v1.1.0 which is still working well.

**Comment by 1038lab** [comment]
update V1.3.0 will fix your issue

**Comment by RhapsodyinBlack** [comment]
Thank you very much, I updated to v1.3.0. The duration and direction issues appear to have been fixed - thank you. 

Unfortunately with the new drag-and-drop vision analyzer I have trouble when I connect a Load Image node directly to Image0 input in the Vision node. If I don't have any image loaded directly through the node, it throws the following Execution Failed error. I get a similar error when connecting to the Image1 input.

Error log
# ComfyUI Error Report
## Error Details
- **Node ID:** 2
- **Node Type:** H3_Vision_Analyzer
- **Exception Type:** TypeError
- **Exception Message:** TypeError: H3_Vision_Analyzer.execute() got an unexpected keyword argument 'ref_images.image_0'

It works if I upload or drag-drop my images directly onto the node, but this means I have to run your custom node standalone and cannot incorporate it into an existing workflow. Is it possible to fix so it still takes inputs externally from the node?

Thank you.
